FROM node:20-alpine

WORKDIR /app
COPY . .

WORKDIR /app/server
RUN npm install

WORKDIR /app/dashboard
RUN npm install && npm run build

WORKDIR /app/docs
RUN npm install && npm run build

WORKDIR /app/server
EXPOSE 3000
CMD ["sh", "-c", "node src/store/migrations/migrate.js && node src/index.js"]